---
title: "Evaluating Toronto's Fire Incidents to Extrapolate Future Occurence Data"
author: 
  - Jimmy Luc
thanks: "Code and data are available at: [https://github.com/rex009x/fire-incidents-toronto](https://github.com/rex009x/fire-incidents-toronto)."
date: today
date-format: long
abstract: "This paper uses publicly available data from [Toronto Open Data](https://open.toronto.ca/) to predict the estimated dollar loss per fire incident in the Toronto area by property use. Further analysis of Toronto Fire Services' response time, area of origin, and various fire prevention measures as considering factors in the estimation. The results reveal a positive correlation between estimated dollar loss and possible causes of the incident, namely, mechanical/electrical failures yielding the highest loss. These findings bring urgency to fire safety as they highlight the importance of proper education, maintenance, and safety inspections. This analysis encourages homeowners, businesses, and property managers to take initiative in order to ensure the well-being of others."
format:
  pdf:
    fig-pos: "H"
toc: true
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(dplyr)
library(ggplot2)
library(here)
```


# Introduction

Fires pose a significant threat to both residential and commercial properties, often resulting in substantial financial losses and, more importantly, endangering lives. Developing a better understanding of the factors that influence the amount in damages per fire incident is crucial for implementing effective fire prevention measures to minimize the impact of such incidents. In this analysis, we delve into the extensive dataset provided by Toronto Open Data [@citeTorontoFireIncidents] which captures fire incidents within the Toronto area as defined by Ontario Fire Marshal (OFM) from 2011-2022. Through this dataset, we aim to predict the estimated dollar loss per fire incident across different property uses and identify the factors contributing to these losses.

The motivation behind this study stems from the necessity to comprehend the underlying patterns and determinants of fire incident costs. By dissecting the data provided by Toronto Open Data, we seek to not only predict the estimated dollar loss but also to identify significant factors influencing these losses. Our analysis extends beyond mere prediction, delving into factors such as Toronto Fire Services' response time, area of origin, and the presence and functionality of fire alarms. These additional variables are essential in understanding the dynamics of fire incidents and formulating informed strategies for fire prevention and mitigation.

Despite the abundance of data available, there remains a gap in comprehensively analyzing the factors contributing to the estimated dollar loss per fire incident in the Toronto area. To address this gap, we employ a data-driven approach, utilizing statistical modeling techniques to uncover patterns and relationships within the dataset. Our methodology involves exploring various factors such as property use, possible causes of the incident (e.g., mechanical/electrical failures), and the presence and functionality of fire alarms. Additionally, we incorporate the number of responding personnel from the Toronto Fire Services (TFS) as a variable to assess its impact on the estimated dollar loss.

The findings of this analysis hold significant implications for fire safety practices and policies in the Toronto area. By understanding the factors influencing the estimated dollar loss per fire incident, stakeholders can prioritize resources and implement targeted interventions to mitigate fire risks effectively. This paper is structured as follows: we first provide an overview of the dataset and variables considered, followed by the methodology employed for analysis. Subsequently, we present our findings, discussing the relationships uncovered and their implications for fire safety. Finally, we conclude by highlighting the importance of our findings and suggesting avenues for future research in this domain.

# Data {#sec-data}

All data collection and analysis was completed using statistical tools such as R [@citeR], and Rstudio IDE [@citeRStudio] to better streamline workflow. The analysis was done using the R program and the following supporting packages: `tidyverse` [@citeTidyverse], `dplyr` [@citeDplyr], `here` [@citeHere], `opendatatoronto` [@citeOpenDataToronto] and `ggplot2` [@citeGgplot2]. Further details regarding data cleaning and analysis will be discussed in the following subsections.


# Model {#sec-model}

Work in progress.


## Model set-up

Work in progress.


### Model justification

Work in progress.


# Results {#sec-results}

Work in progress.


# Discussion {#sec-discussion}

## First discussion point {#sec-first-point}

Work in progress.


## Second discussion point

Work in progress.


## Third discussion point

Work in progress.


## Weaknesses and next steps

Work in progress.


\newpage

\appendix

# Appendix {-}

Work in progress.


# Additional data details

Work in progress.


# Model details {#sec-model-details}

Work in progress.


## Posterior predictive check

Work in progress.


## Diagnostics

Work in progress.


\newpage


# References


